language: c
sudo: required
dist: trusty

# services:
#   - riak

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - ulimit -n 4096
  # riak
  - sudo apt-get -y install build-essential libc6-dev-i386 git
  - sudo apt-get -y install erlang-nox erlang-dev erlang-reltool
  - RIAK_STRIP_V=$(echo $RIAK | sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2/')
  # - wget http://s3.amazonaws.com/downloads.basho.com/riak/$RIAK_STRIP_V/$RIAK/riak-$RIAK.tar.gz
  - echo $RIAK_STRIP_V
  - echo $RIAK
  - wget https://github.com/basho/riak/archive/riak-$RIAK.zip
  - unzip riak-$RIAK.zip
  # - tar zxvf riak-$RIAK.tar.gz
  - cd riak-riak-$RIAK
  - make
  - make rel
  - sed -r --in-place -e 's/^(search) = .*/\1 = on/' rel/riak/etc/riak.conf
  - ./rel/riak/bin/riak start
  - ./rel/riak/bin/riak ping
  - cd -
  - export PATH=$PWD/riak-$RIAK/rel/riak/bin:$PATH

matrix:
  include:
    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.1.3
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.0.6
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}

    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.1.3
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.0.6
      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}

    - env: GHCVER=8.0.1 ARGS="--stack-yaml=.stack-8.0.1.yaml" RIAK=2.1.3
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}
    - env: GHCVER=8.0.1 ARGS="--stack-yaml=.stack-8.0.1.yaml" RIAK=2.0.6
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}

    - env: GHCVER=8.0.2 ARGS="" RIAK=2.1.3
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 ARGS="" RIAK=2.0.6
      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}

    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.1.3
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.0.6
      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

  allow_failures:
    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.1.3
    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.0.6

install:
  - stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
